version: '3.8'
services:
    frontend:
        build: ./frontend
        ports:
            - '3000:3000'
        volumes:
            - ./frontend:/app
            - /app/node_modules
        environment:
            - CHOKIDAR_USEPOLLING=true

    backend:
        build: ./backend
        ports:
            - '5000:5000'
        volumes:
            - ./backend:/app
            - backend_data:/app/data
        environment:
            - FLASK_ENV=development
        env_file:
            - .env.1
        restart: always
volumes:
    backend_data:
