version: '3.8'

services:
    frontend:
        build: ./frontend
        ports:
            - '3000:3000'
        volumes:
            - ./frontend:/app
            - /app/node_modules
        environment:
            - CHOKIDAR_USEPOLLING=true

    backend:
        build: ./backend
        ports:
            - '5000:5000'
        volumes:
            - ./backend:/app
            - config_data:/config
        env_file:
            - .env
        restart: always

volumes:
    config_data:
        name: regexerr_config
